- name: create neonevm group
  group:
    name: neonevm
    system: true
    state: present

- name: create neonevm system user
  user:
    name: neonevm
    system: true
    shell: "/usr/sbin/nologin"
    group: neonevm
    home: /etc/neonevm/

- name: ensure neonevm has access to run docker
  user:
    name: neonevm
    password: 123
    groups: docker
    append: yes

- name: create config dir 
  file:
    path: "{{ neonevm_config_dir }}"
    owner: root
    group: neonevm 
    mode: 0770 
    state: directory

- name: create config dir 
  file:
    path: "{{ postgres_config_dir }}"
    owner: root
    group: neonevm 
    mode: 0770 
    state: directory

# Configure solana key
- name: create neon evm solana keypair if not already present
  command: /root/.local/share/solana/install/releases/1.8.5/solana-release/bin/solana-keygen new -o "{{ neonevm_solana_keypair }}" --no-bip39-passphrase -s
  become: true
  become_user: neonevm
  args:
    chdir: "{{ neonevm_config_dir }}"
    creates: "{{ neonevm_solana_keypair }}"

- name: ensure permissions on neonevm keypair
  file:
    path: "{{ neonevm_solana_keypair }}"
    owner: neonevm
    group: neonevm
    mode: 0600

- name: check neon evm pubkey
  command: /root/.local/share/solana/install/releases/1.8.5/solana-release/bin/solana-keygen pubkey "{{ neonevm_solana_keypair }}"
  register: res_pubkey

- name: save public key hash
  set_fact:
    neonevm_public_key_hash: "{{ res_pubkey.stdout }}"

- debug: msg="Neon EVM Solana public key hash {{ neonevm_public_key_hash }}"

- name: write solana public key to file
  local_action: |
    copy dest=neonevm.pub content="{{ neonevm_public_key_hash }}" 
  become: false

- name: install postgres
  template:
    src: postgres.j2
    dest: /usr/local/bin/postgres
    owner: root
    group: root
    mode: 0755
  notify:
    - restart postgres

- name: install cache postgres service
  template:
    src: postgres.service.j2
    dest: /etc/systemd/system/postgres.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postgres
    
- name: install neonevm
  template:
    src: neonevm.j2
    dest: /usr/local/bin/neonevm
    owner: root
    group: root
    mode: 0755
  notify:
    - restart neonevm

- name: install cache rpc service
  template:
    src: neonevm.service.j2
    dest: /etc/systemd/system/neonevm.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart neonevm

- name: ensure neonevm service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: neonevm
    state: started
    enabled: true

- name: ensure postgres service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: postgres
    state: started
    enabled: true
